moving somethings around

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -6,37 +6,35 @@ set -e
 
 logger -p user.notice -t "slugc[$$]" "language_pack_java java_compile_start"
 
-build_dir=$1
-
-#cat_npm_debug_log() {
-#  test -f $build_dir/npm-debug.log && cat $build_dir/npm-debug.log
-#}
-
-# Output npm debug info on error
-#trap cat_npm_debug_log ERR
-
-# Resolve node version using semver.io
-node_version=0.10.19
-
-# Download node from Heroku's S3 mirror of nodejs.org/dist
-#status "Downloading and installing node"
-#node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
-#curl $node_url -s -o - | tar xzf - -C $build_dir
-
-# Move node (and npm) into ./vendor and make them executable
-#mkdir -p $build_dir/vendor
-#mv $build_dir/node-v$node_version-linux-x64 $build_dir/vendor/node
-#chmod +x $build_dir/vendor/node/bin/*
-#PATH=$PATH:$build_dir/vendor/node/bin
-
-# Install yoeman
-#npm install -g yo
-
 BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
 # parse args
 BUILD_DIR=$1
 CACHE_DIR=$2
 LOGGER_FLAGS=""
+
+cat_npm_debug_log() {
+  test -f $BUILD_DIR/npm-debug.log && cat $BUILD_DIR/npm-debug.log
+}
+
+# Output npm debug info on error
+trap cat_npm_debug_log ERR
+
+# Resolve node version using semver.io
+node_version=0.10.19
+
+# Download node from Heroku's S3 mirror of nodejs.org/dist
+status "Downloading and installing node"
+node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
+curl $node_url -s -o - | tar xzf - -C $BUILD_DIR
+
+# Move node (and npm) into ./vendor and make them executable
+mkdir -p $BUILD_DIR/vendor
+mv $BUILD_DIR/node-v$node_version-linux-x64 $build_dir/vendor/node
+chmod +x $BUILD_DIR/vendor/node/bin/*
+PATH=$PATH:$BUILD_DIR/vendor/node/bin
+
+# Install yoeman
+npm install -g yo
 
 curl --silent --location http://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.tar.gz | tar xz
 . bin/java
@@ -93,7 +91,7 @@ echo " done"
 # change to build dir to run maven
 cd $BUILD_DIR
 
-export MAVEN_OPTS="-Xmx1024m"
+export MAVEN_OPTS="-Xmx1024m $MAVEN_OPTS"
 
 # build app
 BUILDCMD="$CACHE_DIR/.maven/bin/mvn -B -Duser.home=$BUILD_DIR -Dmaven.repo.local=$CACHE_DIR/.m2/repository -s $CACHE_DIR/.m2/settings.xml -DskipTests=true clean install"
